# Generated by Django 5.0 on 2024-07-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('ni_number', models.CharField(max_length=10)),
                ('town_city', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('postcode', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('card_type', models.CharField(max_length=50)),
                ('ccnsg_passport', models.FileField(blank=True, null=True, upload_to='uploads/ccnsg_passports/')),
                ('tica_certificates', models.FileField(blank=True, null=True, upload_to='uploads/tica_certificates/')),
                ('asbestos_certificate', models.FileField(blank=True, null=True, upload_to='uploads/asbestos_certificates/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='uploads/photos/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('registration_no', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Registration Number')),
                ('skillcard', models.FileField(blank=True, null=True, upload_to='uploads/skillcard/')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
            },
        ),
    ]
