# Generated by Django 5.0 on 2024-07-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cardDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=500, null=True)),
                ('meta_decription', models.TextField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('validity', models.CharField(max_length=255)),
                ('decriptions', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('democard', models.FileField(blank=True, null=True, upload_to='uploads/dummycard/')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
