# Generated by Django 5.0 on 2024-07-24 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0002_carddetails_application_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='cardapplyfor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='certificate.carddetails'),
            preserve_default=False,
        ),
    ]
