# Generated by Django 5.0 on 2024-07-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0003_application_cardapplyfor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='registration_no',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
