# Generated by Django 5.0 on 2024-07-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metatag', models.CharField(max_length=255)),
                ('metadescription', models.TextField()),
                ('title', models.CharField(max_length=255)),
                ('shortdescription', models.TextField()),
                ('longdescription', models.TextField()),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
