# Generated by Django 5.0 on 2024-07-29 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memebership', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('asbestos_removal', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('contact_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('postcode', models.CharField(max_length=20)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True, null=True)),
                ('training_contact_name', models.CharField(max_length=255)),
                ('training_contact_email', models.EmailField(max_length=254)),
                ('audit_contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('audit_contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('marketing_contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('marketing_contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('regional_contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('regional_contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('accounts_contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('accounts_contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('additional_telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('additional_postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('company_reg_no', models.CharField(max_length=50)),
                ('vat_reg_no', models.CharField(max_length=50)),
                ('signature', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('health_safety_statement', models.FileField(upload_to='documents/')),
                ('liability_insurance', models.FileField(upload_to='documents/')),
                ('company_registration', models.FileField(upload_to='documents/')),
            ],
        ),
    ]
